### ISSUE TITLE
Talon SRX motors not working

### ISSUE THREAD

**Issue by reitmeie** [MontiPythons-4632/RobotCode2019#1]
We are net getting motors to move.

**Comment by reitmeie** [comment]
The Talon 
SRX Code was removed from the WPILib.  It is provided by CTRE. Here is the instruction.

https://www.ctr-electronics.com/downloads/pdf/Talon%20SRX%20Software%20Reference%20Manual-4.pdf

**Comment by montipythons** [comment]
Using wrong talon driver. Got correct code from CTRE.
